def lt(de: str, en: str) -> dict[str, str]:
    return {
        "de": de,
        "en": en,
    }


def link(de: str, en: str, href: str, variant: str = "secondary") -> dict:
    return {
        "label": lt(de, en),
        "href": href,
        "variant": variant,
    }


def item(
    item_id: str,
    title_de: str,
    title_en: str,
    text_de: str,
    text_en: str,
    icon: str | None = None,
    image_path: str | None = None,
    href: str | None = None,
    meta: dict | None = None,
) -> dict:
    return {
        "id": item_id,
        "title": lt(title_de, title_en),
        "text": lt(text_de, text_en),
        "eyebrow": {},
        "image_path": image_path,
        "image_alt": {},
        "icon": icon,
        "href": href,
        "meta": meta or {},
    }


DEFAULT_CONTENT_PAGES = [
    {
        "slug": "home",
        "title": lt("Klineus", "Klineus"),
        "description": lt(
            "Klineus unterstützt die strukturierte Erhebung und Aufbereitung medizinisch relevanter Patientenangaben.",
            "Klineus supports the structured collection and preparation of medically relevant patient information.",
        ),
        "is_published": True,
        "seo": {
            "title": lt("Klineus", "Klineus"),
        },
        "sections": [
            {
                "id": "hero",
                "type": "hero",
                "order": 1,
                "eyebrow": lt("Klineus", "Klineus"),
                "title": lt("Klineus", "Klineus"),
                "subtitle": lt(
                    "Strukturierte Vorbereitung medizinischer Informationen.",
                    "Structured preparation of medical information.",
                ),
                "body": lt(
                    "Klineus hilft dabei, patientenbezogene Angaben vor einem medizinischen Termin klarer, geordneter und prüfbarer aufzubereiten.",
                    "Klineus helps prepare patient-related information before a medical appointment in a clearer, more structured and reviewable way.",
                ),
                "image_path": "/static/images/hero-medical.png",
                "image_alt": lt(
                    "Digitale medizinische Oberfläche",
                    "Digital medical interface",
                ),
                "links": [],
                "items": [],
                "settings": {},
            },
            {
                "id": "workflow",
                "type": "cards",
                "order": 2,
                "eyebrow": lt("Ablauf", "Workflow"),
                "title": lt(
                    "Von Patientenangaben zu einer klaren medizinischen Übersicht.",
                    "From patient information to a clear medical overview.",
                ),
                "subtitle": {},
                "body": lt(
                    "Klineus strukturiert Angaben, macht relevante Punkte leichter sichtbar und unterstützt eine nachvollziehbare ärztliche Prüfung.",
                    "Klineus structures information, makes relevant points easier to identify and supports traceable physician review.",
                ),
                "image_path": None,
                "image_alt": {},
                "links": [],
                "items": [
                    item(
                        "structured-intake",
                        "Strukturierte Erhebung",
                        "Structured intake",
                        "Relevante Angaben werden in einem klaren Ablauf gesammelt.",
                        "Relevant information is collected in a clear flow.",
                        icon="01",
                    ),
                    item(
                        "clear-overview",
                        "Übersichtliche Aufbereitung",
                        "Clear preparation",
                        "Antworten werden geordnet dargestellt und leichter prüfbar gemacht.",
                        "Answers are organized and made easier to review.",
                        icon="02",
                    ),
                    item(
                        "medical-review",
                        "Ärztliche Prüfung",
                        "Physician review",
                        "Die medizinische Verantwortung bleibt bei der Ärztin oder dem Arzt.",
                        "Medical responsibility remains with the physician.",
                        icon="03",
                    ),
                ],
                "settings": {},
            },
        ],
    },
    {
        "slug": "product",
        "title": lt("Unser Produkt", "Our Product"),
        "description": lt(
            "Klineus strukturiert medizinisch relevante Patientenangaben.",
            "Klineus structures medically relevant patient information.",
        ),
        "is_published": True,
        "seo": {
            "title": lt("Klineus Produkt", "Klineus product"),
        },
        "sections": [
            {
                "id": "hero",
                "type": "hero",
                "order": 1,
                "eyebrow": lt("Unser Produkt", "Our Product"),
                "title": lt(
                    "Klineus strukturiert medizinisch relevante Patientenangaben.",
                    "Klineus structures medically relevant patient information.",
                ),
                "subtitle": lt(
                    "Eine digitale Unterstützung für klare Vorbereitung, bessere Übersicht und prüfbare Dokumentation.",
                    "Digital support for clear preparation, better overview and reviewable documentation.",
                ),
                "body": lt(
                    "Klineus unterstützt medizinische Einrichtungen dabei, Angaben vor einem Termin geordnet zu erfassen, aufzubereiten und übersichtlich darzustellen.",
                    "Klineus helps medical organizations collect, prepare and present information clearly before an appointment.",
                ),
                "image_path": "/static/images/hero-medical.png",
                "image_alt": lt(
                    "Klineus Produktansicht",
                    "Klineus product view",
                ),
                "links": [],
                "items": [],
                "settings": {},
            },
            {
                "id": "features",
                "type": "cards",
                "order": 2,
                "eyebrow": lt("Funktionen", "Features"),
                "title": lt(
                    "Was Klineus leistet.",
                    "What Klineus provides.",
                ),
                "subtitle": {},
                "body": {},
                "image_path": None,
                "image_alt": {},
                "links": [],
                "items": [
                    item(
                        "patient-information",
                        "Strukturierte Patientenangaben",
                        "Structured patient information",
                        "Informationen werden in einem klaren, nachvollziehbaren Ablauf erfasst.",
                        "Information is collected in a clear and traceable flow.",
                        icon="structure",
                    ),
                    item(
                        "medical-overview",
                        "Medizinische Übersicht",
                        "Medical overview",
                        "Relevante Punkte werden geordnet dargestellt und leichter prüfbar gemacht.",
                        "Relevant points are organized and made easier to review.",
                        icon="overview",
                    ),
                    item(
                        "documentation-draft",
                        "Dokumentationsentwurf",
                        "Documentation draft",
                        "Ein möglicher Entwurf kann vorbereitet werden und muss ärztlich geprüft werden.",
                        "A possible draft can be prepared and must be reviewed by a physician.",
                        icon="document",
                    ),
                ],
                "settings": {},
            },
            {
                "id": "boundaries",
                "type": "cards",
                "order": 3,
                "eyebrow": lt("Grenzen", "Boundaries"),
                "title": lt(
                    "Technische Unterstützung ohne Ersatz ärztlicher Verantwortung.",
                    "Technical support without replacing medical responsibility.",
                ),
                "subtitle": {},
                "body": lt(
                    "Klineus stellt keine Diagnose, trifft keine Therapieentscheidung und ersetzt keine ärztliche Prüfung.",
                    "Klineus does not provide diagnosis, treatment decisions or replace physician review.",
                ),
                "image_path": None,
                "image_alt": {},
                "links": [],
                "items": [
                    item(
                        "no-diagnosis",
                        "Keine Diagnose",
                        "No diagnosis",
                        "Klineus bereitet Informationen auf, stellt aber keine Diagnose.",
                        "Klineus prepares information but does not provide a diagnosis.",
                        icon="01",
                    ),
                    item(
                        "no-treatment-decision",
                        "Keine Therapieentscheidung",
                        "No treatment decision",
                        "Behandlungsentscheidungen bleiben vollständig ärztliche Verantwortung.",
                        "Treatment decisions remain fully the physician's responsibility.",
                        icon="02",
                    ),
                    item(
                        "review-required",
                        "Prüfung erforderlich",
                        "Review required",
                        "Jede Ausgabe muss geprüft, korrigiert und freigegeben werden.",
                        "Every output must be reviewed, corrected and approved.",
                        icon="03",
                    ),
                ],
                "settings": {},
            },
        ],
    },
    {
        "slug": "team",
        "title": lt("Über uns", "About Us"),
        "description": lt(
            "Klineus entsteht an der Schnittstelle von Medizin, Produktentwicklung und Technologie.",
            "Klineus is built at the intersection of medicine, product development and technology.",
        ),
        "is_published": True,
        "seo": {
            "title": lt("Über Klineus", "About Klineus"),
        },
        "sections": [
            {
                "id": "hero",
                "type": "hero",
                "order": 1,
                "eyebrow": lt("Über uns", "About Us"),
                "title": lt(
                    "Klineus entsteht an der Schnittstelle von Medizin und Produktentwicklung.",
                    "Klineus is built at the intersection of medicine and product development.",
                ),
                "subtitle": lt(
                    "Unser Ziel ist es, medizinisch relevante Patientenangaben klarer, strukturierter und prüfbarer aufzubereiten.",
                    "Our goal is to make medically relevant patient information clearer, more structured and easier to review.",
                ),
                "body": {},
                "image_path": "/static/images/team.png",
                "image_alt": lt("Klineus Team", "Klineus team"),
                "links": [],
                "items": [],
                "settings": {},
            },
            {
                "id": "roles",
                "type": "cards",
                "order": 2,
                "eyebrow": lt("Fokus", "Focus"),
                "title": lt(
                    "Medizinische Struktur, Produktqualität und verantwortungsvolle Technologie.",
                    "Medical structure, product quality and responsible technology.",
                ),
                "subtitle": {},
                "body": {},
                "image_path": None,
                "image_alt": {},
                "links": [],
                "items": [
                    item(
                        "medical-structure",
                        "Medizinische Struktur",
                        "Medical structure",
                        "Medizinische Anforderungen werden in klare und prüfbare Abläufe übersetzt.",
                        "Medical requirements are translated into clear and reviewable workflows.",
                        icon="medicine",
                    ),
                    item(
                        "product-quality",
                        "Produktqualität",
                        "Product quality",
                        "Der Fokus liegt auf verständlicher Nutzung, klarer Darstellung und stabilen Abläufen.",
                        "The focus is on understandable use, clear presentation and stable workflows.",
                        icon="product",
                    ),
                    item(
                        "responsible-technology",
                        "Verantwortungsvolle Technologie",
                        "Responsible technology",
                        "Technologie soll Transparenz schaffen, aber keine ärztliche Verantwortung ersetzen.",
                        "Technology should create transparency but not replace medical responsibility.",
                        icon="technology",
                    ),
                ],
                "settings": {},
            },
        ],
    },
    {
        "slug": "contact",
        "title": lt("Kontakt", "Contact"),
        "description": lt(
            "Kontaktieren Sie Klineus für Rückfragen, Pilotierung oder Zusammenarbeit.",
            "Contact Klineus for questions, pilots or collaboration.",
        ),
        "is_published": True,
        "seo": {
            "title": lt("Kontakt", "Contact"),
        },
        "sections": [
            {
                "id": "hero",
                "type": "contact",
                "order": 1,
                "eyebrow": lt("Kontakt", "Contact"),
                "title": lt(
                    "Sprechen Sie mit uns über Klineus.",
                    "Talk to us about Klineus.",
                ),
                "subtitle": lt(
                    "Für Pilotprojekte, Partnerschaften oder allgemeine Rückfragen erreichen Sie uns direkt per E-Mail.",
                    "For pilots, partnerships or general questions, you can reach us directly by email.",
                ),
                "body": lt(
                    "Schreiben Sie uns eine kurze Nachricht. Wir melden uns so bald wie möglich zurück.",
                    "Send us a short message. We will get back to you as soon as possible.",
                ),
                "image_path": None,
                "image_alt": {},
                "links": [
                    link(
                        "E-Mail senden",
                        "Send email",
                        "mailto:contact@klineus.de",
                        "primary",
                    ),
                ],
                "items": [
                    item(
                        "email",
                        "E-Mail",
                        "Email",
                        "contact@klineus.de",
                        "contact@klineus.de",
                        icon="email",
                        href="mailto:contact@klineus.de",
                    ),
                    item(
                        "location",
                        "Standort",
                        "Location",
                        "Deutschland",
                        "Germany",
                        icon="location",
                    ),
                    item(
                        "topic",
                        "Anliegen",
                        "Topic",
                        "Pilotierung und Partnerschaft",
                        "Pilots and partnerships",
                        icon="contact",
                    ),
                ],
                "settings": {
                    "show_contact_form": True,
                },
            },
        ],
    },
    {
        "slug": "legal",
        "title": lt("Rechtliches", "Legal"),
        "description": lt(
            "Impressum, Datenschutz und rechtliche Hinweise.",
            "Imprint, privacy and legal information.",
        ),
        "is_published": True,
        "seo": {
            "title": lt("Rechtliches", "Legal"),
        },
        "sections": [
            {
                "id": "hero",
                "type": "hero",
                "order": 1,
                "eyebrow": lt("Rechtliches", "Legal"),
                "title": lt(
                    "Impressum und Datenschutz",
                    "Imprint and Privacy",
                ),
                "subtitle": lt(
                    "Diese Angaben sind Platzhalter und müssen vor produktivem Einsatz rechtlich geprüft werden.",
                    "This information is placeholder content and must be legally reviewed before production use.",
                ),
                "body": {},
                "image_path": None,
                "image_alt": {},
                "links": [],
                "items": [],
                "settings": {},
            },
            {
                "id": "terms",
                "type": "terms",
                "order": 2,
                "eyebrow": lt("Impressum", "Imprint"),
                "title": lt("Impressum", "Imprint"),
                "subtitle": {},
                "body": {},
                "image_path": None,
                "image_alt": {},
                "links": [],
                "items": [
                    item(
                        "provider",
                        "Anbieter",
                        "Provider",
                        "Klineus",
                        "Klineus",
                        icon="01",
                    ),
                    item(
                        "contact",
                        "Kontakt",
                        "Contact",
                        "contact@klineus.de",
                        "contact@klineus.de",
                        icon="02",
                    ),
                    item(
                        "responsibility",
                        "Verantwortlich für den Inhalt",
                        "Responsible for content",
                        "Die vollständigen Angaben zur verantwortlichen Person oder Gesellschaft müssen vor Veröffentlichung ergänzt werden.",
                        "The full details of the responsible person or company must be added before publication.",
                        icon="03",
                    ),
                ],
                "settings": {},
            },
            {
                "id": "privacy",
                "type": "terms",
                "order": 3,
                "eyebrow": lt("Datenschutz", "Privacy"),
                "title": lt("Datenschutz", "Privacy"),
                "subtitle": {},
                "body": lt(
                    "Klineus verarbeitet Daten nur zweckgebunden für strukturierte Vorbereitung und ärztliche Zuordnung.",
                    "Klineus processes data only for structured preparation and physician-side assignment.",
                ),
                "image_path": None,
                "image_alt": {},
                "links": [],
                "items": [
                    item(
                        "data-minimization",
                        "Datensparsamkeit",
                        "Data minimization",
                        "Es sollen nur die Informationen erhoben werden, die für den jeweiligen medizinischen Ablauf erforderlich sind.",
                        "Only information required for the relevant medical workflow should be collected.",
                        icon="privacy",
                    ),
                    item(
                        "medical-assignment",
                        "Ärztliche Zuordnung",
                        "Physician-side assignment",
                        "Patientenname und Fallinformationen dienen der Zuordnung im medizinischen Arbeitsablauf.",
                        "Patient name and case information are used for assignment within the medical workflow.",
                        icon="assignment",
                    ),
                    item(
                        "ai-processing",
                        "KI-Verarbeitung",
                        "AI processing",
                        "Direkte Identifikatoren sollen nicht an KI-Prompts übergeben werden.",
                        "Direct identifiers should not be passed into AI prompts.",
                        icon="ai",
                    ),
                    item(
                        "production-review",
                        "Prüfung vor Produktivbetrieb",
                        "Review before production use",
                        "Vor produktivem Einsatz müssen Datenschutz, IT-Sicherheit, regulatorische Einordnung und klinische Validierung geprüft werden.",
                        "Before production use, privacy, IT security, regulatory classification and clinical validation must be reviewed.",
                        icon="review",
                    ),
                ],
                "settings": {},
            },
        ],
    },
]